name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Scan yaml with kube-linter
      uses: stackrox/kube-linter-action@v1.0.4
      with:
        directory: yamls  # Ajusta al directorio donde est치n tus archivos de configuraci칩n
        format: sarif
        output-file: kube-linter.sarif
      continue-on-error: true

    - name: Setup Polaris
      uses: fairwindsops/polaris/.github/actions/setup-polaris@master
      with:
        version: 5.0.0

    - name: Run Polaris
      run: |
        polaris audit --audit-path ./yamls/ > polaris_output.txt
      continue-on-error: true

    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: yamls  # Ajusta al directorio donde est치n tus archivos de configuraci칩n
        framework: kubernetes  # Puedes especificar un framework particular si es necesario
      continue-on-error: true

    - name: Run kube-score
      run: |
        docker run --rm -v $(pwd):/project zegl/kube-score:latest score yamls/*.yaml > kube_score_output.txt
      continue-on-error: true

    - name: Save validation results
      uses: actions/upload-artifact@v2
      with:
        name: validation-results
        path: |
          kube_linter_output.txt
          polaris_output.txt
          checkov_output.txt  # Ajusta si Checkov genera un archivo con un nombre diferente
          kube_score_output.txt
